name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bison cmake flex gcc make

    - name: build compiler
      run: |
        chmod u+x --recursive script
        script/build.sh
