name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bison cmake flex gcc make

    - name: build compiler
      run: |
        echo "Building the compiler..."
        if ! cmake -S .. -B ../bin; then
          echo "CMake failed!"
          exit 1
        fi

        cd ../bin

        if ! make; then
          echo "Make failed!"
          exit 1
        fi

        echo "All done."
